using NUnit.Framework;
using SportTracksXmlReader;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Xml;
using System.Xml.Linq;
using System.Xml.Serialization;
using Utilities;

namespace Test
{
    public class IOTest
    {
        [TestCase("2008", 476, "2vcNIgAAAAA/AKMFVkL+oPw/APuxQQKfBWJCCSi/QIDTtUEGhAVOQvkn30CAmaJBCHUFckJYKN9AgBCXQQpkBWpCtii/QIAQl0ENRgVaQpYon0BAwZ5BDj8FVkLVSte8AOmaQQ85BWZCs1E+QIAQl0ESJwVeQldTfkDAX49BFwgFWkK2Vj5AgIhZQRvuBF5COFl+QIAmSkEe2gRaQh4t30AAsyNBJLEEVkKoW35AALMjQSmyBE5Ci7n8PwB++kAupAReQjC+/D8AHOtAMoAEYkKgr8+8gAIcQThOBGJCP4Z5P4AUM0E8MQRmQoEx30CAFDNBQRUEYkIzlHk/gJpwQUIQBGJCrjL/QICacEFFCARiQjeVeT8Ar4dBSvADXkKAMv9AQPjjQU7oA25Cesf8P0D5I0JTqgNiQnDH/D8AqetBVoMDXkLfmA9BwFzBQVxJA1JC0DHfQIAQl0FgKQNeQhUy/0CAmnBBZQIDVkKjMt9AgBQzQWvSAnJCkzP/QADwBEFwswJuQq7S/D+AAhxBdJsCVkKdNb9AgBQzQXh8Am5Cvjb/QACzI0F9VwJiQpo3/0CAJkpBgUsCakIVXMe8ADiTQYY9AnJC2DnfQIAOCUKIOgJOQutzfkDgvSlCjA8CakIaOp9AYB85QpDqAWZCe3V+QEBZTEKUzQFiQuWdD0FA9lVClckBYkL9nQ9BoM5ZQpm+AWZCpjz/QEC+iUKfoQFeQpqfD0HAjI5CpIwBWkLjQb9A4OWFQqZ9AWZCmRd6P+D0bkKpagFSQgWEu7xgvEJCrFQBTkIPRr9A4OYMQrEyAWpCkEifQMBfj0G0IQFuQuyTfkCAxTpBuhsBXkJxTN9AgCZKQb8QAVZCgU7fQIACHEHECQFOQlSoD0GAJkpByf0AUkL5Up9AgOloQc3sAFZCrKl+QICIWUHR3gBqQrNWv0CAxTpB1s4AbkJEsX5AgCZKQdyyAGJCbVrfQACvh0HhnQBmQkS4PkCA07VB5pIAVkKIvH5AQG/YQeyPAE5CVUievIBKqkHxiQBuQn9k30CA6WhB9X8AVkI+Zp9AAHZCQfp8AGJC/mj/QIBLeEH+dABaQgDVfkAAOWFB3PgNIgAAAAA1AGoATkLwtQ9BgCZKQQVoAGZC5m2/QIDXUUEKYQBuQp/gPkCAiFlBD1kAWkJqk3s/gMU6QRVTAGZCTqh7P4AUM0EaVABuQnt3/0AAOWFBHkwAUkIteb9AADlhQSNFAFZCdXu/QICacEEpMgBSQvZ9v0AAr4dBLyoAbkLyAH9AgBCXQTUlAGJCohV8P4DWg0E3IwByQiaD/0CAmnBBPAwAXkJQhJ9AgOloQUD9/2FCEIa/QICIWUFH6f9RQk2J/0CAYytBTd//UUIYxg9BALMjQVLT/11C7Bx/QICgDEFXyv9ZQp+Q30CAAhxBXKP/UUK1yA9BgBQzQWJq/3FCjsgPQYBjK0FnM/9NQtNE/j8Ar4dBaCX/aUJ2kZ9AgEqqQWoN/1FCoyN/QEC+0EFs9f5tQhiSv0AAqetBccX+WULMkd9AQDL3QXSf/lVCM8kPQUBcGkJ2iP5tQsSSv0Bg5SVCe1H+YULvJT9AgEVOQoEX/k1CkJl8P8CReEKF/v1ZQlaS30CA4ldCitb9YULTaV28IJYtQo+q/WlCeyE/QMCDFkKTjv1lQnEgP0AASgNCl3D9bUJ4j/9AgAr7QZxF/WFCGflhvEA1xUGhEv1dQkrHD0EA5sxBp9P8aULqjf9AwNDnQaun/FFCqI3fQMBdAUKybvxtQsqM30AArLlBuD38bUIyjP9AgIhZQb0T/GFC6Bd/QIDFOkHC6vttQgFXaLwAWcxAx737WULHi59AALrbQM2C+2VCx4v/QAC620DTTPtxQkSL/0AAlq1A2Br7bUITi59AAFnMQN3o+nFC/BV/QAB++kDiuvplQvlWfD+AAhxB6H/6ZULpit9AgIhZQe1Q+lVCp4q/QIAmSkHyIvptQmIp/j8AOWFB9vz5aUJAip9AgNaDQfrd+WFCzon/QAA5YUHc+Q0iAAAAADUAqfllQpSJ30CA11FBBIf5bUKqxA9BAHZCQQla+VVCAon/QIAmSkEOL/lhQtaIv0AAOWFBEg/5XULNiL9AADlhQRbr+GFCOEV8P4CIWUEaxvhpQkFqbryA11FBHLj4aUKZxA9BgNdRQSGK+GFC9kp8PwB2QkElaPhtQp8Sf0CAJkpBKy74YULViJ9AALMjQS8J+HFCkIjfQIACHEE02vdNQocQf0AAsyNBOLL3WUIOiJ9AgMU6QT53901C34f/QIAmSkFCTfdtQh8QP0AAOWFBRxz3WUJ+ED9AgCZKQU3j9m1CvIi/QIAUM0FTq/ZxQoISf0AAsyNBWXX2YUL1ib9AgAIcQV5K9k1C1BU/QACzI0FjGvZNQtGL/0AAsyNBaOv1WUI1E2e8APAEQW289WlCWTL+PwC620BzhPVZQr8YP0AANJ5AeFT1ZUJAZHw/ADSeQH4c9V1CFI2/QACWrUCE6/RZQveN/0AAWcxAicH0YUJ+j99AABzrQI2i9G1CSOtevAB++kCSfPRhQiuKfD8AuttAl0/0XULXkd9AAFnMQJsq9GFC9JGfQAD4vECfA/RxQiQkf0AA5H5ApcnzWUKmJD9AAH76QKuR82VCpZK/QAAc60CwYPNhQsySv0AAHOtAtiLzVUK4kr9AgIhZQbgI83FC+5N8P4AmSkG96/JVQteS30CAxTpBwOHyZUJMAFm8ALMjQcPa8l1CiSl/QIDFOkHJ5PJZQoW+fD+AYytB0PnyUUKBNn9AgEt4QdcH82lC1O9CvIDWg0HdH/NtQriF/j+AEJdB4jnzZUKUHX0/QG/YQedK81lCuks/QMDi/kHsUvNZQrtPP0DA0OdB8SvzWUKvqN9AQL7QQfIh821CZUZ9P0A1xUH43/JdQiNTP0DAXMFB/bvyXUJL1Q9BQMGeQd36DSIAAAAAGgDD8lVC8Fg/QAA4k0ECyfJdQvVaP0BAwZ5BB8jyVUJLfH0/wCKuQQjH8l1C8a/fQICZokENovJNQquxv0AA/H9BFGbycUK3Uhm8gEt4QRdg8l1CzLP/QAA4k0EcVPJRQtttF7wAcqZBK1DyYUK8q30/wJbUQTBO8mlC3bXfQED440EzTfJhQmPY/j8AqetBuQDvaUK3q99AwPMgwsPo7lFC4Fc/QADmc8HH0e5VQqqs30AAYDbBy9buWUIHrp9AACBgQM3b7m1Cj66fQAC620DT+e5pQk7D/j+A6WhB1vXuUUIJyP4/gIhZQdvI7m1C/rL/QIBjK0HgnO5tQge0v0CAFDNB5mzuTUIOp30/gFEUQetC7nFCttoPQYBjK0HwG+5RQiS2/0CAYytB9e/tZUIYbn9AgBQzQfnN7WVCu7efQIDFOkH/ou1pQo7cD0GAAhxB4PsNIgAAAAA4AIXtUULpud9AgFEUQQZY7XFC6br/QIBjK0ELL+1tQvLdD0GAJkpBEQPtaUIWej9AgMU6QRfg7E1C9JAEvIBjK0EZ3OxhQjLufT+AYytBINXsYUL33g9BALMjQSPI7FlCyXcEvIACHEEquOxdQkrwfT+AFDNBLK3sXUIsvv9AgGMrQTKB7GlCS7/fQIACHEE2YuxdQiWAP0CAFDNBOUjsUULUwJ9AgCZKQTwt7FFCtOAPQQA5YUFBBOxxQlPCv0CAiFlBRtvrTUIThz9AgJpwQUyn62FCm+IPQQD8f0FRf+tRQvAX/z8A/H9BVWDrYUJj4w9BAPx/QVk/61VChcffQAA5YUFdKetxQiUZ/z8AdkJBXyjrUUIs3+m7AHZCQWUx61FCEcOfQIAUM0FqPutlQsXA/0CAmnBBbijraUKS3w9BgJpwQXEX611C4Xw/QIAQl0F15+ptQnD4fT+Ah4tBdtzqbUJEv99AwF+PQXqx6k1CJ8C/QICHi0F/f+pZQgr5+7uA07VBhkrqTUIf4Q9BAHKmQYsk6llCcA3/P8AirkGQAOpdQsER7rvAIq5BltbpcUKUi39AwFzBQZu16WFCQMefQMCW1EGhkulhQsSSf0DAH+BBpYDpcUK8yv9AwB/gQapu6WFCXGrOu8Af4EGwQ+lRQtXN/0BAb9hBtCjpcUKTzp9AwFzBQbgM6VFCxjv/P8BcwUG95uhdQnHP30BANcVBwcboXULCz99AAObMQcaj6G1CVj//P8DQ50HLguhxQt2ff0DAXQFCzmzocUI50P9AQCIHQtND6E1CnIZ+P4AOCULYG+hlQjqJfj+ADglC3P7nXUKn0f9AwF0BQuDk51lCSEn/PwBKA0LlyOdVQiuafj+ACvtB6q3nUULds667wOL+Qe6Z52lCEtX/QCA2BULzhOdVQjqsf0Dg5gxC+WTnTUIm179AIA0iQvtY51VCkNe/QGDlJULh/A0iAAAAADQAOedVQgKyf0DgRjVCBSfnZUIO1H4/IDM3Qgce52FCLWz/P2AfOUIN9eZhQv3bv0CARU5CEd3mTULs5n4/4B1SQha+5m1C1rt/QKBrY0Ibo+ZlQonvD0EgzXJCIIzmXUIW4N9AoAhtQiGK5k1CITZ9u6AIbUIna+ZlQguG/z8gRGdCK1TmVUKbr227IERnQi4/5l1C0xZ/P2Aca0IzIuZRQl+Q/z+ga2NCNwjmaUL75P9AQJNfQj3h5VVCMebfQIB/YUJCweVlQmvnv0BAk19CSJjlTUL1gzq7AApUQk9n5WFCRdQ/QACBSEJWNeVVQq3rn0AgbUpCWhvlbUJy7L9AYLxCQmHo5GVC9/YPQYCoREJmxORZQnHef0DAlEZCbJzkXUKx8J9AAIFIQnJz5FFCr+R/QMCURkJ3T+RRQmzz30CAqERCfC7kWUJ/9J9AQNBAQoEI5GFCxPoPQUDQQEKG6ONtQirtf0CACztCisrjXUJsvX8/gKhEQo6s401CCPnfQEBZTEKSkeNtQib0f0DAlEZCmGvjTUJy+/9AgKhEQplm411CoPv/QODjPkKfVeNZQkn3/z8AgUhCpE3jXULc/w9BQFlMQqpC41FCvQHAQMAxUEKuRuNxQvAC4EDAMVBCs0PjWULuBkBAwDFQQrpE43FCswEAQUBZTEK/I+NpQlYIQEDAlEZCxQHjZUJVBqBAoPc8Qsvl4nFCswiAQCAzN0LQ0eJdQp0KoEDgRjVC1b7iYUKNDOBAYIIvQtmw4nFCORwAQMBaM0LfluJpQjsIEEHAWjNC44biVUIGCQBBwFozQud24mVCxQkQQeBGNULtXOJVQu8KAEFgHzlC8kfiaUKxF6BAIDM3Qvc04lVC8zIAQMBaM0L9G+JRQt4NAEHAWjNC5P0NIgAAAAA7AP/hYUI7CHA7wFozQgbn4U1C6R+gQKBuMUIL0uFtQqUQEEGgbjFCELvhWUI4RgBA4EY1QhWo4WFCdhIQQSAzN0IZmuFxQoYmgEDgRjVCHYvhVUIFFABBwFozQiNz4VVCayqAQGCCL0IoW+FRQmIsoEAgli1CLzHhcUJpXQBAIJYtQjUJ4VVCShgAQaDRJ0I66OBxQm3IgD8gDSJCP8bgaULcGQBBQFwaQkK04HFCX2kAQGBIHEJIi+BhQjRtQEBgSBxCTmXgcULQDOI7QFwaQlNF4FFCDDqAQMCDFkJYJeBNQrjtgD9AvxBCXgHgTUIzPeBAgKsSQmXS31lCXT+gQKCXFEJrrN9lQtJAwEBAXBpCb5TfaULsIBBBYEgcQnCQ31FCbgiBP2BIHEJ2Zd9pQnEhEEGANB5Ce0bfaULEIRBBAHAYQn43321CDETAQMCDFkKFMd9VQmARgT/AgxZCjSLfUUK4RKBAQFwaQpL73lFCLUWgQMCDFkKZxt5VQuaMAEDgICBCna7ebULJjkBA4CAgQp+c3m1CwSMQQWBIHEKkbd5xQs4cgT+AqxJCqTveZUIpjQBAoJcUQq0Y3mlCE0bgQKDRJ0Kx7N1hQusiAEGACztCtcbdVUJ7iwBAYB85Qra73VFCiIsAQKD3PEK4o91xQp4WgT9A0EBCvmLdTUJ7jQBAgOJXQr9b3VVC+xuBP0D2VULFM91hQtlIgEBgvEJCxyTdYUIQJoE/4OM+Qsgd3WlCp7MTPODjPkLJFt1VQi1K4EDg4z5CzQjdZUJUS8BAIJYtQs/73GVCzfMWPCANIkLQ89xRQmpLoEBgSBxC0evcbUJhS+BAwIMWQta/3G1CjEvgQEAiB0LamdxNQoiXQEDA4v5B32zccUJBl0BAAKnrQeNG3F1CBUugQMDQ50HnKdxZQoOUQEAASgNC7ALcYULyScBAQFwaQvHY22FCIC4UPOC9KUL1s9tRQj0lEEHAWjNC+ZLbZUITS4BAoNEnQv5l211C80ugQMBaM0Ln/g0iAAAAADYAQdtNQm0ygT+g0SdCBCLbXUJxmgBAQPkjQggE21lCMk3gQIA0HkIM4tpNQq0mEEFgSBxCEbfaYULWNoE/QFwaQhh42llCSScAQQBwGEIeRNpNQkY9gT9AXBpCJA7aZULXT+BAoJcUQinf2U1CWlDgQADTDkIutNlVQm4oEEEgNgVCNH/ZZUKNKABBwOL+QThb2WVCSlGgQEAy90E9LNlVQqQoAEHA0OdBQ/bYUUJHowBAwB/gQUjK2F1CikWBPwDmzEFNoNhRQumhAECA07VBUXrYXULBUMBAAKy5QVVS2FVCY+IgPABypkFZL9hlQklQgECAmaJBXv3XTUJvUOBAAHKmQWHg11VChlDgQIBKqkFmsddlQotQwEBAwZ5BbHbXVUJ46yE8AHKmQXBN101CKFHgQIDTtUF2FtdVQkaiQECASqpBfNzWXULHokBAgJmiQYGm1llC4ygQQQBypkGDkdZxQvAoAEEAcqZBhnfWcUIOUoBAAHKmQYpW1llCgFLgQMAirkGOPNZhQgJToECASqpBkiDWZUJPU8BAAHKmQZYA1nFC0lOgQIBKqkGb0dVpQrRUwEAAcqZBoZvVXUJ/V4E/wCKuQaZt1VVC31mBP8AirkGrQdVNQpxdgT+A07VBsQvVUUKvsEBAwCKuQbbb1G1CliwAQcAirkG7rNRxQhVa4EBANcVBv4DUcUKWaoE/QIHvQcVN1FFCabcAQMAf4EHJLtRxQn5cwEDAH+BBzvzTZUJqdIE/IDYFQtPV001CD7wAQODmDELYtNNxQgBfoEBAvxBC3ZTTXUKNX8BAoNEnQuKA01FCs1/AQAAKVELqcNNxQrVfgEAgyIhC82vTYUKBf4E/MGWSQvVq01VCQH+BP0Bbk0L3ZdNZQqJfwEBAvolC+0zTVUI+X6BAIERnQvxE03FCLF/gQACnXULn/w0iAAAAADcAJ9NdQuhegECg9zxCBA7TVUKeXoBAAKorQgjo0lFCCl7AQOAgIEIOrNJZQgVewEAgli1CE3XSYUJDLwBBAKorQhhQ0mlCFV+gQODmDEIcJ9JdQkpfwECglxRCIP/RXUKZvgBAQCIHQie80WFCar8AQMBcwUEthdFRQlK/AEDAX49BMVnRUUIDMBBBgIeLQTU20V1CyICBPwCvh0E4HNFNQoeVQDwAr4dBPerQYUJVMABBwF+PQUOu0F1CNcJAQMBfj0FHjdBhQjxh4ECAEJdBTGDQTUJCYeBAgBCXQVEx0FVCfMIAQICHi0FVC9BNQqAwAEEAr4dBWeXPXUJXYaBAAK+HQV63z01CnGGgQAD8f0Fjis9pQp40QzyAmnBBaGLPaUJLhoE/gNdRQW1Jz21ChYiBPwA5YUFwMs9RQvxhgECAiFlBdAzPbUKgYoBAgJpwQXrRzlVCBMdAQICacEGAm85hQhJkoEAAOWFBhW7OUULSZMBAgNaDQYpGzl1Cq2WgQIAQl0GPG85hQhXMAEBAwZ5BlO7NcUI2MwBBAOmaQZm7zWVCbcNNPIDTtUGehc1VQvRm4EDA0OdBn3rNaULqzUBAQDL3QaY9zVlCtTMAQYAOCUKrFM1ZQl7PAEAAqetBsdvMcUL3Z8BAAKnrQbaxzG1CAtBAQADmzEG8esxZQjk0EEFAvtBBv1zMbUJ0o4E/wJbUQcM2zHFCImngQMAf4EHICcxtQozTQEBAge9BzdnLWUI4glQ8gKsSQtKqy11CTDUAQeC9KULTostlQq9qoEAgli1C15/LaUIf2ABAQPkjQtyry01C99wAQMCDFkLgnstlQrTAgT/A+gpC5J7LUUIw5EBAwPoKQumZy1lCQzoQQUAiB0LumctxQkCfbTzAXQFC8pbLTUJQ4oE/gAr7QfaQy2FCIHqgQEAy90H7ZMtdQpQ9EEFA+ONB5wAOIgAAAAAFADbLVUKD9kBAwJbUQQQRy1VCGe2BP8ANyUEH98ppQiF7gEDAXMFBDcnKUUIYfOBAQDXFQQ+9ynFCgnygQMANyUEAAAAAAAAAAA==")]
        [TestCase("2018", 289, "5tgkNQAAAAAsAAAGakJ6Fp9AAAAwQQctBl5CMys+QAAAIEEMWAZSQnNS/D/NzAxBEosGZkJ/E/9AzczsQBi4BmpCbhLfQJqZuUAf3wZuQt0gfkAAAKBAJQsHbkIrHj5AAACgQCs9B2ZCEg7fQGZmpkAxbQdWQjVmeD9mZqZAN5YHWkKUwfS8MzOzQDyeB1pC0BJ+QAAAwEBCeAdaQsAH30CamdlARHIHYkIBB99AAADgQEqPB2pCmAT/QGZm5kBQswdWQqICv0AzM/NAVtgHakLXAL9AAADgQFz/B15C4v6eQGZmxkBfFAhmQkv6+z+amblAZUMIWkIY+z1AzcysQGt2CHJCOvp9QGZmpkByoghiQhL93kCamdlAdKgIUkJTfg9BzczsQHzVCHJCIDACvQAAEEGD2ghaQnt8D0EAAMBAifIIUkLI9v5AAABAQY4eCWZCWvWeQAAAqEGVTwlWQhagBb1mZoZBm3wJXkLzeQ9BZmZWQaGsCVpCY3AGvQAAUEGn4AlOQlDkBr0zM1NBrRIKckKpeA9BMzMzQbNACmZCK8H7PwAAMEG5cwpSQl3v/kCamSlBv6cKVkIr3T1AMzNDQcXZClJCp9t9QAAAYEHLDgtmQg3t3kAzMzNB0TULWkIv695AMzNTQddZC1ZChum+QDMzm0HeiQtuQhik+z+amclB5LwLbkKQvgu9zczUQenjC1ZCKOe+QDMz00Hw8AtSQojkvkAzM7tB9vILckLLiPs/Zma+Qf0BDG5ChiwQvWZmtkHp2SQ1AAAAAC0ADAxaQq26PUCamaFBByQMckJioRK9MzOrQQs1DG5Ckdi+QJqZkUESTQxaQlLWnkAAAGBBGG4MTkIU1f5AmplJQR2gDGJCuKp2PwAAQEEnywxWQoTuFL2amTlBKNIMbkL0q31AAAAwQS4bDWJCPVX7PwAAgEEzUg1eQprV3kCamalBOYcNVkKs1Z5Azcz8QT+8DWpC5Kx9QM3MFEJF7g1iQhuvPUAAABxCSx0OZkJcbA9BzcwgQlFKDlZCZdneQJqZNUJZeA5iQh/ankCamUFCXqsObkJa295AAABoQmLcDnJCuLh9QDMzd0JnDw9qQn27fUAzM3dCbTgPVkKD355AAABkQnNWD05CXcM9QM3MVEJ4fQ9SQgtmDr3NzFBCfqsPTkJZcg9BMzNHQoTUD15C5OXeQJqZOUKLABBSQtJVDL1mZjJCkisQVkJ3ovs/AAA0QphhEGpCSOneQGZmHkKekRByQkDq/kBmZhJCpMIQckJ56t5AzcwAQqn2EHJCC3UPQZqZ8UGuKBFuQt7p/kAzM/tBtF0RWkIwp/s/Zma2QbqREWJCy0l3P2ZmjkHAwRFeQijo3kBmZmZBxuoRckIYkAy9zcw8QcwQEm5CK5X7PzMzI0HSOBJqQozjvkBmZjZB2GQSUkL34Z5AZmZmQd6SEm5CyQZ3P5qZeUHoxBJeQvvBfUAAAIhB68sSckJ74b5AAABwQe7YEmJC93APQZqZWUHx5xJeQpbhnkDNzDxB+A4TYkLwbw9BZmY2Qf5FE2pCt9++QAAAYEHs2iQ1AAAAACkAcxNaQswBdz8AAIhBBqMTUkJnwj1AZmaOQQvRE1JC4HAPQTMzm0ERBBROQiRxD0FmZqZBFzcUVkJ3xT1AAACwQR5tFE5CBeO+QJqZqUEknhRyQh/HfUAzM7tBKtAUXkLwzA29zczMQS7uFF5CwZP7P83MzEE2IhViQsnlvkCamZlBPFQVYkKfyz1AAACIQUKDFVZCYix3PzMzg0FItBVuQmDlvkAzM3NBTuYVWkLvyT1AzcxsQVQVFlpC0c0NvTMzc0FaRhZqQpTj3kCamWlBYl4WVkLKwn1AZmZWQWlrFlZC3b09QGZmJkFviRZqQja5PUCamRlBdbcWckKLbQ9BZmYGQXvsFnJClLQ9QAAAAEGBHhdWQmqzfUDNzAxBh1AXbkLY2L5AAAAgQY2DF3JCddieQDMzM0GTqhdWQpSzfUDNzDxBm9sXTkLNtX1Azcw8QaINGHJCuNveQJqZSUGoPRhuQlbcnkBmZnZBr24YYkKMbg9BmpmBQbafGG5CXh8RvTMzc0G91RheQt+7PUCamYFBxAsZXkLvBhG9ZmZ2Qcs9GV5CQbt9QDMzi0HSchluQrRnEb3NzKRB2KIZZkKP3N5AMzOjQd7RGWJCy9v+QAAAmEHk+BluQui0PUAAAIBB6g0aVkIHYfs/MzNTQfANGlpC3moPQTMzQ0H29hlSQhinfUCamUlB/N4ZZkIUjHY/ZmZGQe7bJDUAAAAALADQGVpCEs++QM3MTEEH1RlmQj1mD0FmZjZBDesZTkLI0Bq9ZmYmQRMTGlpCWcj+QDMzM0EZOBpuQkMZ+z+amUlBHlwaXkJhYg9BAABQQSSHGmJCd2EPQQAAQEEqsRpaQqlgD0EzM1NBMN8aXkKgAyC9MzNjQTYOG25C077eQAAAYEE8PRtqQqS9nkCamUlBQmsbZkJ9vP5AAABQQUiVG2pCVbu+QGZmdkFKoRtSQj+7/kAAAIhBTq8bTkJrtiG9AACYQVS8G3JCL7++QJqZqUFaxRtSQmyDPUAzM6tBYL0bVkIqxJ5AZma+QWajG2pCRsbeQAAAuEFsdxtiQngf+z9mZq5BckYbXkLeyP5AzcycQXgSG2pCbZJ9QJqZeUF94xpiQgzJ/kDNzGxBg64aXkK0yJ5AAABgQYl8GmZClJA9QGZmVkGPShpWQmIg+z8AAFBBlRkaWkL0yJ5AZmZWQZz7GWJCxcq+QGZmjkGj7BluQj3NvkAAAKBBqfYZTkJxPvs/AACgQa8DGnJC+WgPQc3MfEG1GxpOQizU3kAAAHBBuysaakI/rT1AZmaGQcEkGmJCEdn+QAAAoEHHERpeQjvbvkBmZrZBzeUZXkImuT1AMzO7QdO3GWZCHVERvWZmrkHZhRlSQnnwdj/NzJxB31MZTkJlvT1AZmaWQeUdGU5CvPl2PzMzg0Hr6BhmQpX5dj8AAGBB8bQYYkIrfPs/mplZQfd/GGpCfL19QJqZSUH9SxhOQpS8PUCamTlB8dwkNQAAAAApABoYUkK+3Z5AmpkpQQbsF2pClHgRvQAAQEENvRduQtK3PUAAAIhBE5IXVkI4tX1AmpmBQRlgF1ZCZtqeQJqZaUEfMBdmQsjavkDNzFxBJQAXYkLYtj1AZmZGQSvRFlJCO7h9QAAAMEEyqRZuQtnd/kCamTlBOZUWckKUwD1AzcxMQUCGFnJC2+KeQM3MXEFHaRZaQm9yD0EAAHBBTT0WckLJ5f5AAABgQVMLFmpCcObeQGZmRkFZ2xVeQv7mnkBmZlZBX6UVZkI1555Ampk5QWR1FVpC+p37P5qZKUFmYxVOQo3nvkAAACBBbCwVUkKO555AZmYGQXL4FHJC7jl3P83MDEF3yhRWQoWTDL0zMzNBfZYUYkLKAg29AABAQYNiFE5CCMt9QJqZOUGKMxRiQvzk3kAAAIhBkP4TYkJE5P5AzcxsQZbJE15CxsY9QGZmNkGbnhNeQvfEPUBmZjZBoWwTXkJp4Z5AAAAQQac5E25C48F9QM3MHEGuChNmQpnDPUDNzAxBvO0SYkJL475AMzMDQcK4ElJCZov7PwAAwEDHiRJuQgHHPUDNzIxAzVYSckIEJHc/MzMzQNMuElpCS+b+QDMzk0DZBBJaQvbnnkDNzMxA390RYkKl6b5AZmYGQeWzEU5CMeu+QM3MDEHrghFWQo/YfUCamdlA8VQRbkIV2n1Ampn5QPglEXJCdu3+QGZmVkHx3SQ1AAAAACoA9RBSQi12Cb1mZqZBCMcQYkJY7P5AZmbmQQ6YEFJC6q/7P2Zm7kEVaBBeQghadz8zMwNCHDkQckI7dQ9BzcwgQiIKEHJCJkx3PzMzN0Ip1g9mQqfbC70zM0tCLa4PbkIB555AmplBQjOED2ZCG5b7P5qZWUI6YQ9uQupxD0EzM2tCRD4PZkLOhvs/zcyEQkoYD3JCHv92PzMzi0JS+A5aQjm8fUDNzJxCWb4OZkIu3d5AAACKQlyPDk5CM9yeQGZmYkJgXw5iQje2fUBmZjpCZC4OUkK02r5AMzMrQmn9DVZCGtq+QDMzE0Jvzg1qQnPZ3kCamQFCdJ0NckIocRO9MzPbQXprDWJC6LE9QGZmvkGEQg1mQpjYnkAAANhBiA0NZkJc175AMzPTQYn9DFpChIwUvc3M5EGRuQxWQrzV3kAzMz9CmI4MUkJpaw9Bmpk9Qp5yDG5CMNneQJqZBUKlVgxeQnLbnkAAAARCq0kMbkIT3t5AAADwQbE+DHJCKsE9QDMz80G3OgxaQiHj3kAzM/tBvSgMXkIULHc/zczkQcMKDG5Cr+f+QAAA4EHJ9QteQpbTPUAAAAhCz8oLVkLJ6p5AZmYOQtaWC1JCl+veQJqZGULcZwtSQsrsnkBmZhJC4TILUkLl7f5AAADwQegBC1pCNO/eQDMzy0Hu0ApWQhp4D0FmZr5B9qQKYkKt8d5AZmYSQvx2ClJCo/LeQJqZHUL03iQ1AAAAACAAQwpmQlzz/kDNzCBCBhYKXkKJ0fs/mpkdQgvnCVJCIvXeQJqZCUIRtAlSQr7rfUDNzABCF38JWkJ27T1AmpnhQR1KCWZCstv7PwAAwEEkFgleQqL3/kBmZqZBKfgIckLz8n1AAACYQS/1CFZCFvy+QM3MlEE41whyQiL3+z+amWlBPaEIYkJv/f5AzczMv0JzCF5CsPzeQAAAwMBIPghOQmgPAb1mZibAThUIakJQ/n1AzcxMPlXqB1ZCiwD/QDMzk0BcxQdSQs4Bv0AAACBBYb0HVkKesPu8AAAwQWeqB3JCfAafQM3MTEFusAdyQlQRfkAzM1NBdL4HTkLbCv9AZmZWQXqXB1pCD2Z4PwAAUEGAZgdmQjQO/0BmZhZBhzcHVkJ7D99AzcwcQY0MB2pCuyF+QAAAMEGT4wZaQioSn0AzM7NAmbMGYkJqE59AzcxMQJ6LBm5CWKV4PwAAgD+heAZaQmoVv0AAAADAplgGckLwYem8ZmbGwKhKBlZCJ+/ovGZmpsCuOQZmQghm/D8zM5PArzkGYkLVGb9AZmZmwAAAAAAAAAAA")]
        public void GPSData_Valid_Encoding(string year, int dataLength, string binaryData)
        {
            Console.WriteLine($"Testing serialization of {year} data");
            var gpsRoute = new GPSRoute
            {
                TrackData = new TrackData
                {
                    Version = 4,
                    Data = binaryData
                },
            }; 

            gpsRoute.DecodeBinaryData();
            Assert.That(gpsRoute.ElevationData.Count, Is.EqualTo(dataLength), "Elevation data not correct size");

            gpsRoute.TrackData.Data = string.Empty;
            gpsRoute.EncodeBinaryData();
            Assert.That(gpsRoute.TrackData.Data, Is.EqualTo(binaryData), "Encoded data doesn't match source");
        }

        /// <summary>
        /// This is used to split a corrupt logbook into individual activity files and attempt to
        /// deserialize. The problematic file can then be identified.
        /// </summary>     
        public void Split_Activities_And_Deserialize()
        {
           XNamespace ns = "urn:uuid:D0EB2ED5-49B6-44e3-B13C-CF15BE7DD7DD";
            var elements = XDocument.Load(@"C:\temp\cutdownlogbook.logbook3");
            var linqToXmlActivity = elements.Descendants(ns + "Activity").Where(e => (string)e.Attribute("hasStartTime") == "true");

            int index = 1;
            foreach (var activity in linqToXmlActivity)
            {
                var file = Path.Combine(@"C:\temp\activities", $"{index++}.xml");
                activity.Save(file);
            }
        
            XmlSerializer xmlSerializer = new(typeof(Activity));

            for (int loadIndex = 1; loadIndex < index; loadIndex++)
            {
                var loadDoc = new XmlDocument();
                var file = Path.Combine(@"C:\temp\activities", $"{loadIndex}.xml");
                loadDoc.Load(file);

                var loadElement = loadDoc.DocumentElement;
                try
                {
                    var activity = xmlSerializer.Deserialize(new XmlNodeReader(loadElement)) as Activity;
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Failed to load {loadIndex}.xml : {ex}");
                }
            }
        }

        public void Deserialize_Valid_FitFile()
        {
            var expected = "Pending setup of data";
            var fitDeserializer = new FitDeserializer();

            var gpsRoute = new GPSRoute();
            gpsRoute.TrackData = new TrackData { Version = 4 };
            gpsRoute.TrackData.Data = expected;
            gpsRoute.DecodeBinaryData();

            fitDeserializer.Deserialize(@"Pending setup of data");
            var activity = fitDeserializer.Activity;
            var gpsData = activity.GPSRoute.TrackData.Data;

            // There was a difference in the Latitude Data
            // Caused by rounding differences. Fixed by calulating in double then converting to float at the end
            // Call CompareArrays to investigate
            CompareArrays(activity.GPSRoute.LatitudeData, gpsRoute.LatitudeData);

            Assert.That(gpsData, Is.EqualTo(expected));
        }

        /// <summary>
        /// Use for debugging
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="lhs"></param>
        /// <param name="rhs"></param>
        public void CompareArrays<T>(List<T> lhs, List<T> rhs)
        {
            for (int i = 0; i < lhs.Count; i++)
            {
                if (lhs[i].ToString() != rhs[i].ToString())
                {
                    Console.WriteLine($"ERROR! {i}: LHS {lhs[i]} - RHS {rhs[i]}");
                }
            }
        }
    }
}